from interface.errors.data_object_error import DataObjectError


class BlobError(DataObjectError):
    pass
